{
 "title": "NGINX Exporter Dashboard",
 "tags": [
  "nginx",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "NGINX Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "NGINX Up" }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "irate(nginx_connections_active[5m])",
     "legendFormat": "Active Connections"
    },
    {
     "expr": "irate(nginx_connections_reading[5m])",
     "legendFormat": "Reading"
    },
    {
     "expr": "irate(nginx_connections_writing[5m])",
     "legendFormat": "Writing"
    },
    {
     "expr": "irate(nginx_connections_waiting[5m])",
     "legendFormat": "Waiting"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "irate(nginx_http_requests_total[5m])",
     "legendFormat": "HTTP Requests"
    }
   ]
  }
 ]
}